# Generated by Django 4.2.7 on 2023-11-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atm_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atm",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=100),
        ),
        migrations.AlterField(
            model_name="atm",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=100),
        ),
    ]
